- src/app/pages/about/about.component.html
> About content

- src/app/pages/career/career.component.html
- src/styles.css
> container fix

- angular.json
- src/app/@theme/css/style.css
- src/app/pages/career/career-info/career-info.component.html
- src/app/pages/career/career-info/career-info.component.ts
- src/app/pages/career/career.component.html
- src/styles.css
> Work slider design

- src/app/@theme/css/style.css
- src/app/pages/about/about.component.html
- src/app/pages/contact/contact.component.html
- src/app/pages/services/services.component.html
- src/styles.css
aos animation in about, services, contact page design also animation
> aos animation in about, services, contact page design also animation

- src/app/@theme/css/style.css
- src/app/@theme/js/scripts.js
- src/app/pages/career/career-info/career-info.component.html
- src/app/pages/career/career.component.html
- src/app/pages/contact/contact.component.html
- src/app/pages/home/home.component.html
home page and career page animation
> home page and career page animation

- src/app/@theme/services/work.service.ts
- src/app/@theme/shared.module.ts
- src/app/pages/add-developer/add-developer.component.html
- src/app/pages/need-team/need-team.component.ts
- src/app/pages/pages.module.ts
- src/app/pages/work/work.component.ts
> need team add work api bind

- src/app/@theme/shared.module.ts
- src/app/app.component.html
- src/app/app.module.ts
- src/app/pages/about/about.component.html
- src/app/pages/contact/contact.component.html
- src/app/pages/home/home.component.html
- src/app/pages/need-team/need-team.component.html
- src/app/pages/need-team/need-team.component.ts
- src/app/pages/pages.module.ts
> add nav header

- src/app/pages/about/about.component.html
- src/app/pages/career/career.component.html
- src/app/pages/contact/contact.component.html
- src/app/pages/home/home.component.html
- src/app/pages/need-team/need-team.component.html
> connectivity

- src/app/pages/career/career-info/career-info.component.html
- src/app/pages/need-team/need-team.component.html
- src/app/pages/need-team/need-team.component.ts
multiple file upload and add developer condition and career info file message change
> multiple file upload and add developer condition

- package-lock.json
- package.json
- src/app/@theme/shared.module.ts
- src/app/app.component.html
- src/app/pages/about/about.component.html
- src/app/pages/add-developer/add-developer.component.html
- src/app/pages/add-developer/add-developer.component.ts
- src/app/pages/career/career-info/career-info.component.ts
- src/app/pages/contact/contact.component.html
- src/app/pages/home/home.component.html
- src/app/pages/need-team/need-team.component.html
- src/app/pages/need-team/need-team.component.ts
- src/styles.css
> date-picker validation

- src/app/@theme/css/style.css
- src/app/app.component.html
- src/app/pages/career/career-info/career-info.component.html
- src/app/pages/need-team/need-team.component.html
- src/app/pages/need-team/need-team.component.ts
> mobile view changes

- package-lock.json
- package.json
- src/app/@theme/css/style.css
- src/app/@theme/shared.module.ts
- src/app/app.component.ts
- src/app/pages/about/about.component.ts
- src/app/pages/add-developer/add-developer.component.html
- src/app/pages/career/career-info/career-info.component.html
- src/app/pages/career/career-info/career-info.component.ts
- src/app/pages/career/career.component.ts
- src/app/pages/career/career.module.ts
- src/app/pages/contact/contact.component.ts
- src/app/pages/home/home.component.html
- src/app/pages/home/home.component.ts
- src/app/pages/need-team/need-team.component.html
- src/app/pages/need-team/need-team.component.ts
- src/app/pages/services/services.component.ts
- src/app/pages/work/work.component.ts
- src/styles.css
> loader carousel dropdown

- src/app/app.component.html
- src/app/pages/about/about.component.html
- src/app/pages/add-developer/add-developer.component.html
- src/app/pages/career/career-info/career-info.component.html
- src/app/pages/career/career-info/career-info.component.ts
- src/app/pages/contact/contact.component.html
- src/app/pages/contact/contact.component.ts
- src/app/pages/home/home.component.html
- src/app/pages/need-team/need-team.component.html
- src/app/pages/work/work.component.html
- src/styles.css
changes according 2nd test , client saying remove, contact length, footer colon changes , ng select width , remove require field, etc..
> changes according 2nd test

- src/app/@theme/css/style.css
- src/app/app.component.html
- src/app/pages/career/career-info/career-info.component.html
- src/app/pages/career/career.component.html
- src/app/pages/contact/contact.component.html
- src/app/pages/home/home.component.html
- src/app/pages/need-team/need-team.component.html
- src/app/pages/portfolio/portfolio-info/portfolio-info.component.html
- src/app/pages/portfolio/portfolio-info/portfolio-info.component.ts
- src/app/pages/portfolio/portfolio.component.html
- src/app/pages/portfolio/portfolio.component.ts
- src/styles.css
> changes according to test

- src/app/app.component.html
- src/app/pages/career/career-info/career-info.component.html
- src/app/pages/contact/contact.component.html
> connect join

- src/app/pages/portfolio/portfolio-info/portfolio-info.component.html
- src/app/pages/portfolio/portfolio-info/portfolio-info.component.ts
multiple-image in portfolio info
> multiple-image in portfolio info

- src/app/app.component.html
- src/app/pages/add-developer/add-developer.component.html
- src/app/pages/career/career-info/career-info.component.html
- src/app/pages/career/career-info/career-info.component.ts
- src/app/pages/career/career.component.html
- src/app/pages/contact/contact.component.html
- src/app/pages/contact/contact.component.ts
- src/app/pages/home/home.component.html
- src/app/pages/need-team/need-team.component.html
- src/app/pages/need-team/need-team.component.ts
- src/app/pages/portfolio/portfolio-info/portfolio-info.component.ts
- src/app/pages/portfolio/portfolio.component.ts
- src/styles.css
functionality changes and design fix
> functionality changes and design fix

- src/app/@theme/css/style.css
- src/app/pages/career/career-info/career-info.component.html
> nav cursor changes

- src/app/pages/about/about.component.html
- src/app/pages/career/career.component.html
- src/app/pages/contact/contact.component.html
- src/app/pages/home/home.component.html
- src/app/pages/need-team/need-team.component.html
- src/app/pages/portfolio/portfolio-info/portfolio-info.component.html
- src/app/pages/portfolio/portfolio-info/portfolio-info.component.ts
- src/app/pages/portfolio/portfolio.component.css
- src/app/pages/portfolio/portfolio.component.html
- src/app/pages/services/services.component.html
- src/index.html
- src/styles.css
meta-data loader-quote flip-card
> meta-data loader-quote flip-card

- src/app/@theme/css/plugins/pe-icon-7-stroke.css
> Remove api

- package-lock.json
- package.json
- src/app/@theme/js/scripts.js
- tsconfig.app.json
> mouse resolve

- package-lock.json
- package.json
- src/app/@theme/services/cache.service.ts
- src/app/@theme/services/cacheInterceptor.ts
- src/app/@theme/shared.module.ts
- src/app/app.module.ts
- src/app/pages/home/home.component.ts
- src/app/pages/portfolio/portfolio-info/portfolio-info.component.html
> caching home-client-comment

- src/app/@theme/services/career.service.ts
- src/app/@theme/services/home.service.ts
- src/app/@theme/services/work.service.ts
- src/app/pages/about/about.component.ts
- src/app/pages/career/career-info/career-info.component.ts
- src/app/pages/home/home.component.ts
- src/app/pages/portfolio/portfolio-info/portfolio-info.component.ts
> get-post request-body change

- src/app/@theme/services/cacheInterceptor.ts
- src/app/pages/about/about.component.html
- src/app/pages/career/career-info/career-info.component.html
- src/app/pages/career/career-info/career-info.component.ts
- src/app/pages/home/home.component.html
- src/app/pages/portfolio/portfolio-info/portfolio-info.component.html
- src/app/pages/portfolio/portfolio-info/portfolio-info.component.ts
- src/app/pages/portfolio/portfolio.component.html
- src/app/pages/services/services.component.html
- src/app/pages/services/services.component.ts
> image-video url final changes

- src/app/@theme/css/style.css
- src/app/pages/need-team/need-team.component.ts
- src/app/pages/portfolio/portfolio-info/portfolio-info.component.ts
- src/app/pages/services/services.component.ts
Console remove moto-fix -mobile view
> Console remove

- src/app/@theme/js/scripts.js
> Remove -script-js

- src/app/@theme/css/style.css
- src/app/pages/services/services.component.html
- src/styles.css
services pages responsive design changes
> services pages responsive design changes

- src/app/@theme/css/style.css
- src/app/pages/services/services.component.html
- src/app/pages/services/services.component.ts
> show more show less

- src/app/@theme/css/style.css
- src/app/@theme/js/scripts.js
- src/app/pages/home/home.component.html
- src/app/pages/services/services.component.html
- src/app/pages/services/services.component.ts
get a call changes and services page changes
> get a call changes and services page changes

- src/app/@theme/css/style.css
- src/app/pages/services/services.component.html
- src/styles.css
services section margin bottom
> services section margin bottom
